# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://sachin-suresh.github.io"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: "/sa-portfolio"

# Title of the Site
title: Sachin Suresh | Portfolio
# Description of the Site
description: "Explore UX writing, documentation, and technical writing samples by Sachin Suresh."
# URL of Image of the Site
site-image: https://sachin-suresh.github.io/sa-portfolio/assets/images/og-image.jpg

# Keywords of the Site
site-keywords: technical writing, technical editing, UX writing, API documentation, documentation samples, Sachin Suresh
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sach7411@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: sachin-mca
github_username:
youtube_channel_id:
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: "Sachin Suresh"
# URL for the Image of the Author
author-image:

# 60 Words About the Author
author-about: # Updated in about.html

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Sachin-Suresh

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Include standalone verification or special files
include:
  - googlec53646d4e8e1c312.html

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

under_maintenance: false